#Workflow to deploy docker image

name: CI

on:
  schedule:
    -cron: '38 18 16 4 *'

jobs:
  docker-build:
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Build and push Docker images
      if: steps.release.outputs.tag_name
      uses: docker/build-push-action@v2
      run: docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
      with:
        username:   ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
        registry:   ${{ secrets.DOCKER_REGISTRY }} 
        repository: ldcamachoc/docker-react
        context: .
        file: Dockerfile.dev         
        tags: ldcamachoc/docker-react:latest, ldcamachoc/docker-react:1.0.0    
    -
      name: test
      run: docker run -e CI=true ldcamachoc/docker-react npm run test