#Workflow to deploy docker image

name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username:   ${{ secrets.DOCKER_USERNAME }}
          password:   ${{ secrets.DOCKER_PASSWORD }}         
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2        
        with:        
          repository: ldcamachoc/docker-react
          context: .
          file: Dockerfile.dev         
          tags: ldcamachoc/docker-react:1.0.0       
      -
        name: test
        run: docker run -e CI=true ldcamachoc/docker-react npm run test