#Workflow to deploy docker image

name: CI

on:
  push:
    branches:
      - 'master'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2    
      #Docker
      -
        name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1 
        with:
          username:   ${{ secrets.DOCKER_USERNAME }}
          password:   ${{ secrets.DOCKER_PASSWORD }}         
      - 
        name: Build and push Docker images
        if: success()
        id: docker_build
        uses: docker/build-push-action@v2.3.0        
        with:        
          repository: ldcamachoc/docker-react
          context: ./
          file: ./Dockerfile.dev         
          tags: ldcamachoc/docker-react:1.0.0,ldcamachoc/docker-react:latest
          push: true       
      -
        name: test
        run: docker run -e CI=true ldcamachoc/docker-react:1.0.0 npm run test
        run: npm run test